build(deps): bump sentence-transformers from 5.1.0 to 5.1.1 (#162)
Bumps
[sentence-transformers](https://github.com/UKPLab/sentence-transformers)
from 5.1.0 to 5.1.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/UKPLab/sentence-transformers/releases">sentence-transformers's
releases</a>.</em></p>
<blockquote>
<h2>v5.1.1 - Explicit incorrect arguments, fixes for multi-GPU,
evaluator, and hard negative</h2>
<p>This patch makes Sentence Transformers more explicit with incorrect
arguments and introduces some fixes for multi-GPU processing,
evaluators, and hard negatives mining.</p>
<p>Install this version with</p>
<pre lang="bash"><code># Training + Inference
pip install sentence-transformers[train]==5.1.1
<h1>Inference only, use one of:</h1>
<p>pip install sentence-transformers==5.1.1
pip install sentence-transformers[onnx-gpu]==5.1.1
pip install sentence-transformers[onnx]==5.1.1
pip install sentence-transformers[openvino]==5.1.1
</code></pre></p>
<h2>Error if unused kwargs is passed &amp; <code>get_model_kwargs</code>
(<a
href="https://redirect.github.com/UKPLab/sentence-transformers/issues/3500">#3500</a>)</h2>
<p>Some SentenceTransformer or SparseEncoder models support custom
model-specific keyword arguments, such as <a
href="https://huggingface.co/jinaai/jina-embeddings-v4">jinaai/jina-embeddings-v4</a>.
As of this release, calling <code>model.encode</code> with keyword
arguments that aren't used by the model will result in an error.</p>
<pre lang="python"><code>&gt;&gt;&gt; from sentence_transformers import
SentenceTransformer
&gt;&gt;&gt; model = SentenceTransformer(&quot;all-MiniLM-L6-v2&quot;)
&gt;&gt;&gt; model.encode(&quot;Who is Amelia Earhart?&quot;,
normalize=True)
Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
File &quot;[sic]/torch/utils/_contextlib.py&quot;, line 116, in
decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File &quot;[sic]/SentenceTransformer.py&quot;, line 983, in encode
    raise ValueError(
ValueError: SentenceTransformer.encode() has been called with additional
keyword arguments that this model does not use: ['normalize']. As per
SentenceTransformer.get_model_kwargs(), this model does not accept any
additional keyword arguments.
</code></pre>
<p>Quite useful when you, for example, accidentally forget that the
parameter to get normalized embeddings is
<code>normalize_embeddings</code>. Prior to this version, this parameter
would simply quietly be ignored.</p>
<p>To check which custom extra keyword arguments may be used for your
model, you can call the new <code>get_model_kwargs</code> method:</p>
<pre lang="python"><code>&gt;&gt;&gt; from sentence_transformers import
SentenceTransformer, SparseEncoder
&gt;&gt;&gt;
SentenceTransformer(&quot;all-MiniLM-L6-v2&quot;).get_model_kwargs()
[]
&gt;&gt;&gt; SentenceTransformer(&quot;jinaai/jina-embeddings-v4&quot;,
trust_remote_code=True).get_model_kwargs()
['task', 'truncate_dim']
&gt;&gt;&gt;
SparseEncoder(&quot;opensearch-project/opensearch-neural-sparse-encoding-doc-v3-distill&quot;).get_model_kwargs()
['task']
</code></pre>
<p><strong>Note:</strong> You can always pass the <code>task</code>
parameter, it's the only model-specific parameter that will be quietly
ignored. This means that you can always use <code>model.encode(...,
task=&quot;query&quot;)</code> and <code>model.encode(...,
task=&quot;document&quot;)</code>.</p>
<h2>Minor Features</h2>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/UKPLab/sentence-transformers/commit/22ff509464b431f6f084b48ae58bfc3fc8210e4e"><code>22ff509</code></a>
Release v5.1.1</li>
<li><a
href="https://github.com/UKPLab/sentence-transformers/commit/5ad8a44ee4b24f3e2ef9b3db77d6ecc54d51e1ac"><code>5ad8a44</code></a>
Merge branch 'master' into v5.1-release</li>
<li><a
href="https://github.com/UKPLab/sentence-transformers/commit/1def8d3d6289e72bfa6a6a48592b1342053e6ff2"><code>1def8d3</code></a>
Fix the number of missing negatives in mine_hard_negatives (<a
href="https://redirect.github.com/UKPLab/sentence-transformers/issues/3504">#3504</a>)</li>
<li><a
href="https://github.com/UKPLab/sentence-transformers/commit/2e077fb3b033b394bcc82781397c5e54c560754c"><code>2e077fb</code></a>
fix: add makedirs to informationretrievalevaluator (<a
href="https://redirect.github.com/UKPLab/sentence-transformers/issues/3516">#3516</a>)</li>
<li><a
href="https://github.com/UKPLab/sentence-transformers/commit/20c48207f36e81a993fdce872911bf37b97bf18d"><code>20c4820</code></a>
Fix:Import SentenceTransformer class explicitly in losses module (<a
href="https://redirect.github.com/UKPLab/sentence-transformers/issues/3521">#3521</a>)</li>
<li><a
href="https://github.com/UKPLab/sentence-transformers/commit/7240b334b7aa068f298693764a7cd0a0afb9ed24"><code>7240b33</code></a>
[<code>feat</code>] add get_model_kwargs method; throw error if unused
kwarg is passed (...</li>
<li><a
href="https://github.com/UKPLab/sentence-transformers/commit/560cc336b1c483da2c8994312c6e1e7b824f9792"><code>560cc33</code></a>
always pass <code>input_ids</code>, <code>attention_mask</code>,
<code>token_type_ids</code>, <code>inputs_embeds</code> ...</li>
<li><a
href="https://github.com/UKPLab/sentence-transformers/commit/bd91098bd6f84fb2fd29a4954abc65d175d912b1"><code>bd91098</code></a>
Update rasyosef/splade-mini MSMARCO and BEIR-13 benchmark scores in
pretraine...</li>
<li><a
href="https://github.com/UKPLab/sentence-transformers/commit/ad8d27de4520b814b2526afcd69f427f2365eb0b"><code>ad8d27d</code></a>
Add Support for Knowledgeable Passage Retriever (KPR) (<a
href="https://redirect.github.com/UKPLab/sentence-transformers/issues/3495">#3495</a>)</li>
<li><a
href="https://github.com/UKPLab/sentence-transformers/commit/5b18f3672c0f3eb5617451b12b2d3fcafd08e043"><code>5b18f36</code></a>
[<code>feat</code>] Use encode_document and encode_query in
mine_hard_negatives (<a
href="https://redirect.github.com/UKPLab/sentence-transformers/issues/3502">#3502</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/UKPLab/sentence-transformers/compare/v5.1.0...v5.1.1">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=sentence-transformers&package-manager=uv&previous-version=5.1.0&new-version=5.1.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>